### ISSUE TITLE
thermite does not work on T420 laptop

### ISSUE THREAD

**Issue by nimbius** [danielrobbins/thermite#1]
multiple "error writing" warnings for max_temp.  

what kernel modules are required to run this package?

**Comment by danielrobbins** [comment]
Currently, you'll need intel_pstate built in, and thinkpad_acpi and intel_thermalclamp

**Comment by nimbius** [comment]
all these have been compiled.  currently running linux kernel 4.9.9 with 8gb ram.

**Comment by danielrobbins** [comment]
modprobe them.

**Comment by nimbius** [comment]
all modules are compiled into the kernel.  would the functionality change if i made them loadable modules instead?

**Comment by danielrobbins** [comment]
It shouldn't. I will update the code to do some diagnostics as it currently does none.

Does /proc/acpi/ibm/fan exist?

**Comment by nimbius** [comment]
fan exists.  enabled, speed and level are all reported.

**Comment by danielrobbins** [comment]
OK, I have updated thermite.py so it should print out much more diagnostic information, and also tell us what it is having trouble writing to. Give this one a try and it should give us more information about what's going on on your system.

**Comment by nimbius** [comment]
debug info:
DEBUG:root:Found 4 temperature sensors.
DEBUG:root:Checking to see if Intel PState driver is available
DEBUG:root:Checking to see if Intel PState driver is available
DEBUG:root:Found Intel PState driver.
DEBUG:root:Checking to see if ThinkPad fan is enabled
DEBUG:root:Checking to see if ThinkPad fan is enabled
DEBUG:root:Thinkpad fan enabled. Setting start level to 3.
CRITICAL:root:error writing level 3 to /proc/acpi/ibm/fan
DEBUG:root:Attempting to locate Intel PowerClamp cooling device
DEBUG:root:Found Intel PowerClamp
CRITICAL:root:error writing level 0 to /proc/acpi/ibm/fan
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 17, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
CRITICAL:root:error writing level 1 to /proc/acpi/ibm/fan
INFO:root:max_temp: 44000, clamp 0, fan 1, cpu 16, var 0
^C^XTraceback (most recent call last):

**Comment by danielrobbins** [comment]
Are you running thermite as root? If not, you will need to be root for thermite to control the fan.
If you are, please attach the output of 'cat /proc/acpi/ibm/fan' as it is likely that different kernels have different APIs for the fan and I need to support both.

**Comment by nimbius** [comment]
im running thermite as root, however my fan device is 3 lines.  kernel is gentoo-sources 4.9.9


status:		enabled
speed:		3225
level:		auto

**Comment by danielrobbins** [comment]
Try doing this as root:

echo 'level 7' > /proc/acpi/ibm/fan

Then cat /proc/acpi/ibm/fan. Does it report level 7?

**Comment by nimbius** [comment]
http://www.thinkwiki.org/wiki/How_to_control_fan_speed
looks like this is disabled by default in the module.  ill try enabling it today and provide results.  if positive, would you like a pull request and a patch for checking module state?

**Comment by danielrobbins** [comment]
Aha! That makes sense. Yes, I made that modification locally and totally forgot about it. Yes, I'd love a patch.

**Comment by nimbius** [comment]
completed testing during emerge/compile of the latest firefox.  Fan seemed aggressively responsive to the CPU.  works as intended!
